version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.hidroworks_dev.rule=Host(`dev.hidroworks.hu`)
      - traefik.http.routers.hidroworks_dev.entrypoints=websecure
      - traefik.http.routers.hidroworks_dev.tls=true
      - traefik.http.routers.hidroworks_dev.tls.certresolver=lets-encrypt
      - traefik.port=3000
    networks:
      - router_web
    environment:
      - NEXT_PUBLIC_STRAPI_API_URL=http://hw_backend:1337

networks:
  router_web:
    external: true
